databases:
  - name: iihcollege
    plan: free
    databaseName: iihc-database
    user: Pxel

services:
  - type: web
    plan: free
    name: iihcollege
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m  iihc_website_portal.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: iihcollege
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 5