# Generated by Django 5.1.2 on 2024-10-25 15:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=20, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('phone', models.CharField(max_length=13, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('lrn', models.CharField(max_length=12, unique=True, verbose_name='Learner Reference Number (LRN)')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, verbose_name='Sex')),
                ('mother_tongue', models.CharField(max_length=30, verbose_name='Mother Tongue')),
                ('religion', models.CharField(max_length=30, verbose_name='Religion')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('learning_mode', models.CharField(choices=[('Modular', 'Modular'), ('Face to face', 'Face to Face'), ('Online', 'Online'), ('Hybrid', 'Hybrid')], max_length=15, verbose_name='Learning Mode')),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Mobile Wallet', 'Mobile Wallet')], max_length=15, verbose_name='Payment Method')),
                ('strand', models.CharField(choices=[('STEM', 'STEM'), ('ABM', 'ABM'), ('HUMSS', 'HUMSS'), ('GAS', 'GAS'), ('TVL', 'TVL')], max_length=5, verbose_name='Strand')),
                ('branch', models.CharField(choices=[('La Forteza Campus', 'IIH COLLEGE - La Forteza Campus'), ('Zabarte Fairview Campus', 'IIH COLLEGE - Zabarte Fairview Campus'), ('Novaliches Campus', 'IIH COLLEGE - Novaliches Campus'), ('Brixton Camarin Campus', 'IIH COLLEGE - Brixton Camarin Campus')], max_length=50, verbose_name='Branch')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
