# Generated by Django 5.1.2 on 2024-11-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='IIH College', max_length=60),
        ),
    ]
