# Generated by Django 5.1.2 on 2024-10-26 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_portal', '0002_student_emergency_contact_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
    ]
