# Generated by Django 5.1.2 on 2024-10-31 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_portal', '0003_remove_student_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='lrn',
        ),
    ]
