# Generated by Django 5.1.2 on 2024-11-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_portal', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tvl_specifics',
            field=models.CharField(blank=True, choices=[('HE - Cookery', 'HE - Cookery'), ('HE - Tourism', 'HE - Tourism'), ('ICT', 'ICT')], max_length=15, null=True, verbose_name='Specifics'),
        ),
    ]
