# Generated by Django 5.1.2 on 2024-11-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_portal', '0007_teacher_alter_message_options_message_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='default_password', max_length=50),
        ),
    ]
