# Generated by Django 5.1.2 on 2024-11-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_portal', '0011_anothermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnotherModel',
        ),
    ]
