# Generated by Django 5.1.2 on 2024-11-15 10:11

import django.db.models.deletion
import website_portal.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_portal', '0013_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Enter your comment here.')),
                ('image', models.ImageField(help_text='Upload an image (max 5MB).', upload_to='community_images/', validators=[website_portal.validators.validate_image_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment', models.FileField(blank=True, help_text='Upload an optional file (max 10MB).', null=True, upload_to='attachments/', validators=[website_portal.validators.validate_file_size])),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website_portal.teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Community',
                'verbose_name_plural': 'Communities',
                'ordering': ['-created_at'],
            },
        ),
    ]
