# Generated by Django 5.1.2 on 2024-11-16 01:27

import website_portal.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_portal', '0014_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='post',
            field=models.TextField(default='', help_text='Enter your post here.'),
        ),
        migrations.AddField(
            model_name='community',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image (max 5MB).', null=True, upload_to='community_images/', validators=[website_portal.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='community',
            name='comment',
            field=models.TextField(blank=True, help_text='Enter your comment here.', null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image (max 5MB).', null=True, upload_to='community_images/', validators=[website_portal.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, help_text='Upload an optional file (max 10MB).', null=True, upload_to='attachments/', validators=[website_portal.validators.validate_file_size]),
        ),
    ]
