# Generated by Django 5.1.2 on 2024-11-16 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_portal', '0015_community_post_community_visibility_message_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website_portal.teacher'),
        ),
    ]
