# Generated by Django 5.1.2 on 2024-11-16 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_portal', '0017_alter_community_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='comment',
            field=models.TextField(blank=True, help_text='Enter your comment here.', null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='post',
            field=models.TextField(help_text='Enter your post here.', null=True),
        ),
    ]
